import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { usePatientProfile } from "@/hooks/use-patient-profile";
import { useAuth } from "@/hooks/use-auth";
import { Download, Mail, FileText, Activity, Thermometer, Calendar, Loader2, Sparkles, Stethoscope } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import type { Appointment, Symptom, Reading, PatientProfile } from "@shared/schema";

function formatDate(date: Date | string | null): string {
  if (!date) return "Not specified";
  return new Date(date).toLocaleDateString("en-US", { 
    year: "numeric", 
    month: "long", 
    day: "numeric" 
  });
}

function generateHealthReport(
  profile: PatientProfile | null,
  appointments: Appointment[],
  symptoms: Symptom[],
  readings: Reading[]
): string {
  const lines: string[] = [];
  const now = new Date();
  
  lines.push("=".repeat(60));
  lines.push("HEALTHPREP - HEALTH DATA REPORT");
  lines.push("=".repeat(60));
  lines.push(`Generated: ${now.toLocaleDateString()} at ${now.toLocaleTimeString()}`);
  lines.push("");

  if (profile) {
    lines.push("-".repeat(40));
    lines.push("PATIENT INFORMATION");
    lines.push("-".repeat(40));
    lines.push(`Name: ${profile.name}`);
    lines.push(`Relationship: ${profile.relationship}`);
    if (profile.dateOfBirth) lines.push(`Date of Birth: ${formatDate(profile.dateOfBirth)}`);
    if (profile.gender) lines.push(`Gender: ${profile.gender}`);
    if (profile.bloodType) lines.push(`Blood Type: ${profile.bloodType}`);
    if (profile.allergies) lines.push(`Allergies: ${profile.allergies}`);
    if (profile.conditions) lines.push(`Conditions: ${profile.conditions}`);
    if (profile.medications) lines.push(`Medications: ${profile.medications}`);
    if (profile.emergencyContact) lines.push(`Emergency Contact: ${profile.emergencyContact} (${profile.emergencyPhone || "No phone"})`);
    lines.push("");
  }

  if (appointments.length > 0) {
    lines.push("-".repeat(40));
    lines.push("APPOINTMENTS");
    lines.push("-".repeat(40));
    appointments.slice(0, 10).forEach((apt, i) => {
      lines.push(`${i + 1}. ${apt.title}`);
      lines.push(`   Date: ${formatDate(apt.appointmentDate)}`);
      if (apt.doctorName) lines.push(`   Doctor: ${apt.doctorName}`);
      if (apt.specialty) lines.push(`   Specialty: ${apt.specialty}`);
      if (apt.location) lines.push(`   Location: ${apt.location}`);
      if (apt.notes) lines.push(`   Notes: ${apt.notes}`);
      lines.push("");
    });
  }

  if (symptoms.length > 0) {
    lines.push("-".repeat(40));
    lines.push("RECENT SYMPTOMS");
    lines.push("-".repeat(40));
    symptoms.slice(0, 15).forEach((symptom, i) => {
      lines.push(`${i + 1}. ${symptom.name} (Severity: ${symptom.severity}/10)`);
      lines.push(`   Date: ${formatDate(symptom.recordedAt)}`);
      if (symptom.notes) lines.push(`   Notes: ${symptom.notes}`);
      lines.push("");
    });
  }

  if (readings.length > 0) {
    lines.push("-".repeat(40));
    lines.push("RECENT HEALTH READINGS");
    lines.push("-".repeat(40));
    readings.slice(0, 15).forEach((reading, i) => {
      lines.push(`${i + 1}. ${reading.type}: ${reading.value} ${reading.unit || ""}`);
      lines.push(`   Date: ${formatDate(reading.recordedAt)}`);
      if (reading.notes) lines.push(`   Notes: ${reading.notes}`);
      lines.push("");
    });
  }

  lines.push("-".repeat(40));
  lines.push("DISCLAIMER");
  lines.push("-".repeat(40));
  lines.push("This report is for informational purposes only and does not");
  lines.push("constitute medical advice. Always consult with a healthcare");
  lines.push("professional for medical decisions.");
  lines.push("");
  lines.push("Generated by HealthPrep - Your Doctor Visit Companion");
  
  return lines.join("\n");
}

export default function ExportData() {
  const { user } = useAuth();
  const { selectedProfile, isChildMode } = usePatientProfile();
  const { toast } = useToast();
  const [email, setEmail] = useState("");
  const [includeAppointments, setIncludeAppointments] = useState(true);
  const [includeSymptoms, setIncludeSymptoms] = useState(true);
  const [includeReadings, setIncludeReadings] = useState(true);
  const [isExporting, setIsExporting] = useState(false);

  const { data: appointments = [] } = useQuery<Appointment[]>({
    queryKey: ["/api/appointments"],
  });

  const { data: symptoms = [] } = useQuery<Symptom[]>({
    queryKey: ["/api/symptoms"],
  });

  const { data: readings = [] } = useQuery<Reading[]>({
    queryKey: ["/api/readings"],
  });

  const emailMutation = useMutation({
    mutationFn: async (data: { email: string; report: string }) => {
      const response = await apiRequest("POST", "/api/export/email", data);
      if (!response.ok) {
        if (response.status === 401) {
          throw new Error("Please sign in to share your health report");
        } else if (response.status === 503) {
          throw new Error("Email service is not available. Please download the report instead");
        } else if (response.status === 400) {
          throw new Error("Please enter a valid email address");
        } else if (response.status === 429) {
          throw new Error("Too many requests. Please wait a moment and try again");
        } else {
          throw new Error("Unable to send email. Please try downloading the report instead");
        }
      }
      return response;
    },
    onSuccess: () => {
      toast({
        title: "Email sent!",
        description: `Your health report has been sent to ${email}`,
      });
      setEmail("");
    },
    onError: (error: Error) => {
      toast({
        title: "Unable to send email",
        description: error.message || "Please check your email address and try again.",
        variant: "destructive",
      });
    },
  });

  const handleDownload = () => {
    setIsExporting(true);
    try {
      const filteredAppointments = includeAppointments ? appointments : [];
      const filteredSymptoms = includeSymptoms ? symptoms : [];
      const filteredReadings = includeReadings ? readings : [];

      const report = generateHealthReport(
        selectedProfile,
        filteredAppointments,
        filteredSymptoms,
        filteredReadings
      );

      const blob = new Blob([report], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `healthprep-report-${new Date().toISOString().split("T")[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({
        title: "Download started!",
        description: "Your health report is downloading.",
      });
    } catch (error) {
      toast({
        title: "Download failed",
        description: "Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsExporting(false);
    }
  };

  const handleSendEmail = () => {
    if (!email) {
      toast({
        title: "Email required",
        description: "Please enter an email address.",
        variant: "destructive",
      });
      return;
    }

    const filteredAppointments = includeAppointments ? appointments : [];
    const filteredSymptoms = includeSymptoms ? symptoms : [];
    const filteredReadings = includeReadings ? readings : [];

    const report = generateHealthReport(
      selectedProfile,
      filteredAppointments,
      filteredSymptoms,
      filteredReadings
    );

    emailMutation.mutate({ email, report });
  };

  return (
    <div className="container mx-auto p-6 max-w-4xl space-y-6">
      <div className="flex items-center gap-3">
        <div className={`flex h-12 w-12 items-center justify-center rounded-lg ${isChildMode ? "bg-gradient-to-br from-purple-500 to-pink-500" : "bg-primary"}`}>
          <FileText className="h-6 w-6 text-white" />
        </div>
        <div>
          <h1 className="text-2xl font-bold">Export & Share</h1>
          <p className="text-muted-foreground">
            {isChildMode ? "Share your health info with grown-ups!" : "Download or email your health data"}
          </p>
        </div>
        {isChildMode && (
          <Badge variant="secondary" className="ml-auto bg-gradient-to-r from-purple-100 to-pink-100 text-purple-700">
            <Sparkles className="h-3 w-3 mr-1" />
            Kid Mode
          </Badge>
        )}
      </div>

      {selectedProfile && (
        <Card className={isChildMode ? "border-purple-200" : ""}>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              {isChildMode && <Stethoscope className="h-5 w-5 text-primary" />}
              {isChildMode ? `${selectedProfile.name}'s Health Report` : `Report for ${selectedProfile.name}`}
            </CardTitle>
            <CardDescription>
              {isChildMode 
                ? "Pick what you want to share from your health info!" 
                : "Select which data to include in your export"
              }
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <div className="flex items-center space-x-3">
                <Checkbox 
                  id="appointments" 
                  checked={includeAppointments}
                  onCheckedChange={(checked) => setIncludeAppointments(checked as boolean)}
                  data-testid="checkbox-appointments"
                />
                <Label htmlFor="appointments" className="flex items-center gap-2 cursor-pointer">
                  <Calendar className="h-4 w-4 text-blue-500" />
                  {isChildMode ? "Doctor Visits" : "Appointments"} 
                  <Badge variant="outline">{appointments.length}</Badge>
                </Label>
              </div>

              <div className="flex items-center space-x-3">
                <Checkbox 
                  id="symptoms" 
                  checked={includeSymptoms}
                  onCheckedChange={(checked) => setIncludeSymptoms(checked as boolean)}
                  data-testid="checkbox-symptoms"
                />
                <Label htmlFor="symptoms" className="flex items-center gap-2 cursor-pointer">
                  <Activity className="h-4 w-4 text-orange-500" />
                  {isChildMode ? "How I Felt" : "Symptoms"}
                  <Badge variant="outline">{symptoms.length}</Badge>
                </Label>
              </div>

              <div className="flex items-center space-x-3">
                <Checkbox 
                  id="readings" 
                  checked={includeReadings}
                  onCheckedChange={(checked) => setIncludeReadings(checked as boolean)}
                  data-testid="checkbox-readings"
                />
                <Label htmlFor="readings" className="flex items-center gap-2 cursor-pointer">
                  <Thermometer className="h-4 w-4 text-green-500" />
                  {isChildMode ? "My Measurements" : "Health Readings"}
                  <Badge variant="outline">{readings.length}</Badge>
                </Label>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      <div className="grid md:grid-cols-2 gap-6">
        <Card className={isChildMode ? "border-blue-200" : ""}>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Download className="h-5 w-5" />
              {isChildMode ? "Save to Computer" : "Download Report"}
            </CardTitle>
            <CardDescription>
              {isChildMode 
                ? "Get a file you can show to your doctor!" 
                : "Download a text file with your health data"
              }
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button 
              onClick={handleDownload} 
              className="w-full"
              disabled={isExporting}
              data-testid="button-download"
            >
              {isExporting ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  {isChildMode ? "Getting ready..." : "Preparing..."}
                </>
              ) : (
                <>
                  <Download className="h-4 w-4 mr-2" />
                  {isChildMode ? "Download My Report" : "Download Report"}
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        <Card className={isChildMode ? "border-pink-200" : ""}>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Mail className="h-5 w-5" />
              {isChildMode ? "Send to a Grown-up" : "Email Report"}
            </CardTitle>
            <CardDescription>
              {isChildMode 
                ? "Email your health info to mom, dad, or your doctor!" 
                : "Send your health report to an email address"
              }
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">
                {isChildMode ? "Email Address" : "Recipient Email"}
              </Label>
              <Input
                id="email"
                type="email"
                placeholder={isChildMode ? "mom@email.com" : "doctor@example.com"}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                data-testid="input-email"
              />
            </div>
            <Button 
              onClick={handleSendEmail} 
              className="w-full"
              disabled={emailMutation.isPending || !email}
              data-testid="button-send-email"
            >
              {emailMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  {isChildMode ? "Sending..." : "Sending..."}
                </>
              ) : (
                <>
                  <Mail className="h-4 w-4 mr-2" />
                  {isChildMode ? "Send My Report" : "Send Email"}
                </>
              )}
            </Button>
            {!user && (
              <p className="text-xs text-muted-foreground text-center">
                Email sending requires you to be logged in.
              </p>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
