import { useState, useRef } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useMutation, useQuery } from "@tanstack/react-query";
import { 
  ClipboardList, 
  Sparkles, 
  Printer, 
  Download,
  AlertCircle,
  ChevronRight,
  Loader2,
  Calendar,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { MedicalDisclaimer } from "@/components/medical-disclaimer";
import { apiRequest } from "@/lib/queryClient";
import type { Appointment } from "@shared/schema";

const formSchema = z.object({
  condition: z.string().min(2, "Please describe your condition or reason for visit"),
  symptoms: z.string().min(2, "Please describe your symptoms"),
  medications: z.string().optional(),
  appointmentId: z.string().optional(),
});

type FormData = z.infer<typeof formSchema>;

interface GeneratedQuestions {
  questions: Array<{
    category: string;
    items: string[];
  }>;
  redFlags: string[];
}

export default function QuestionsGenerator() {
  const [generatedData, setGeneratedData] = useState<GeneratedQuestions | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const { data: appointments } = useQuery<Appointment[]>({
    queryKey: ["/api/appointments"],
  });

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      condition: "",
      symptoms: "",
      medications: "",
      appointmentId: "",
    },
  });

  const generateMutation = useMutation({
    mutationFn: async (data: FormData) => {
      const sanitizedData = {
        ...data,
        appointmentId: data.appointmentId && data.appointmentId !== "none" ? data.appointmentId : undefined,
      };
      const response = await apiRequest("POST", "/api/questions/generate", sanitizedData);
      if (!response.ok) {
        if (response.status === 401) {
          throw new Error("Please sign in to generate questions");
        } else if (response.status === 429) {
          throw new Error("Too many requests. Please wait a moment and try again");
        } else {
          throw new Error("Unable to generate questions. Please try again later");
        }
      }
      return await response.json() as GeneratedQuestions;
    },
    onSuccess: (data) => {
      setGeneratedData(data);
    },
  });

  const onSubmit = (data: FormData) => {
    generateMutation.mutate(data);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    if (!generatedData) return;
    
    let content = "QUESTIONS FOR MY DOCTOR\n";
    content += "========================\n\n";
    content += `Condition: ${form.getValues("condition")}\n`;
    content += `Symptoms: ${form.getValues("symptoms")}\n`;
    if (form.getValues("medications")) {
      content += `Medications: ${form.getValues("medications")}\n`;
    }
    content += "\n";

    if (generatedData.redFlags && generatedData.redFlags.length > 0) {
      content += "RED FLAGS TO MENTION IMMEDIATELY\n";
      content += "--------------------------------\n";
      generatedData.redFlags.forEach((flag) => {
        content += `• ${flag}\n`;
      });
      content += "\n";
    }

    generatedData.questions.forEach((category) => {
      content += `${category.category.toUpperCase()}\n`;
      content += "-".repeat(category.category.length) + "\n";
      category.items.forEach((q) => {
        content += `• ${q}\n`;
      });
      content += "\n";
    });

    content += "\n---\n";
    content += "Generated by HealthPrep - For informational purposes only.\n";
    content += "This is not medical advice. Please consult your healthcare provider.\n";

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `doctor-questions-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container max-w-4xl py-6 space-y-6">
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <ClipboardList className="h-6 w-6 text-primary" />
          <h1 className="text-2xl font-bold tracking-tight">Questions for My Doctor</h1>
        </div>
        <p className="text-muted-foreground">
          Prepare thoughtful questions for your next medical appointment. Enter your information below 
          and we'll generate relevant questions to discuss with your healthcare provider.
        </p>
      </div>

      <MedicalDisclaimer />

      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" />
              Your Information
            </CardTitle>
            <CardDescription>
              Tell us about your condition, symptoms, and medications
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                <FormField
                  control={form.control}
                  name="appointmentId"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Link to Appointment (Optional)</FormLabel>
                      <Select onValueChange={(v) => field.onChange(v && v !== "none" ? v : undefined)} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-appointment">
                            <SelectValue placeholder="Select an upcoming appointment" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="none">No appointment selected</SelectItem>
                          {appointments?.map((apt) => (
                            <SelectItem key={apt.id} value={apt.id.toString()}>
                              <div className="flex items-center gap-2">
                                <Calendar className="h-3 w-3" />
                                {apt.title} - {new Date(apt.appointmentDate).toLocaleDateString()}
                              </div>
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormDescription>
                        Optionally link these questions to an appointment
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="condition"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Condition or Reason for Visit</FormLabel>
                      <FormControl>
                        <Input
                          placeholder="e.g., High blood pressure, Annual checkup, Persistent headaches"
                          data-testid="input-condition"
                          {...field}
                        />
                      </FormControl>
                      <FormDescription>
                        What is your main health concern or reason for seeing the doctor?
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="symptoms"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Current Symptoms</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="e.g., Frequent headaches in the morning, dizziness when standing up, occasional fatigue"
                          className="min-h-[100px] resize-none"
                          data-testid="input-symptoms"
                          {...field}
                        />
                      </FormControl>
                      <FormDescription>
                        Describe the symptoms you're experiencing
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="medications"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Current Medications (Optional)</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="e.g., Lisinopril 10mg daily, Aspirin 81mg daily, Vitamin D supplements"
                          className="min-h-[80px] resize-none"
                          data-testid="input-medications"
                          {...field}
                        />
                      </FormControl>
                      <FormDescription>
                        List any medications, vitamins, or supplements you're taking
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <Button 
                  type="submit" 
                  className="w-full"
                  disabled={generateMutation.isPending}
                  data-testid="button-generate"
                >
                  {generateMutation.isPending ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Generating Questions...
                    </>
                  ) : (
                    <>
                      <Sparkles className="mr-2 h-4 w-4" />
                      Generate Questions
                    </>
                  )}
                </Button>
              </form>
            </Form>
          </CardContent>
        </Card>

        <div className="space-y-4" ref={printRef}>
          {generateMutation.isPending && (
            <Card className="border-dashed">
              <CardContent className="flex flex-col items-center justify-center py-12">
                <Loader2 className="h-8 w-8 animate-spin text-primary mb-4" />
                <p className="text-muted-foreground">Generating personalized questions...</p>
                <p className="text-sm text-muted-foreground mt-1">This may take a few seconds</p>
              </CardContent>
            </Card>
          )}

          {generateMutation.isError && (
            <Card className="border-destructive">
              <CardContent className="flex flex-col items-center justify-center py-8">
                <AlertCircle className="h-8 w-8 text-destructive mb-4" />
                <p className="text-destructive font-medium" data-testid="text-error-message">
                  {generateMutation.error?.message || "Failed to generate questions"}
                </p>
                <p className="text-sm text-muted-foreground mt-1">
                  {generateMutation.error?.message?.includes("sign in") 
                    ? "Click the login button above to get started"
                    : "Please try again"}
                </p>
              </CardContent>
            </Card>
          )}

          {generatedData && !generateMutation.isPending && (
            <>
              {generatedData.redFlags && generatedData.redFlags.length > 0 && (
                <Card className="border-destructive/50 bg-destructive/5">
                  <CardHeader className="pb-3">
                    <CardTitle className="flex items-center gap-2 text-destructive">
                      <AlertCircle className="h-5 w-5" />
                      Red Flags to Mention
                    </CardTitle>
                    <CardDescription>
                      Discuss these concerns with your doctor immediately
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2">
                      {generatedData.redFlags.map((flag, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <ChevronRight className="h-4 w-4 mt-0.5 text-destructive shrink-0" />
                          <span className="text-sm">{flag}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              <Card>
                <CardHeader className="pb-3">
                  <div className="flex items-center justify-between flex-wrap gap-2">
                    <CardTitle className="flex items-center gap-2">
                      <ClipboardList className="h-5 w-5 text-primary" />
                      Questions to Ask
                    </CardTitle>
                    <div className="flex items-center gap-2 no-print">
                      <Button 
                        variant="outline" 
                        size="sm" 
                        onClick={handlePrint}
                        data-testid="button-print"
                      >
                        <Printer className="h-4 w-4 mr-1" />
                        Print
                      </Button>
                      <Button 
                        variant="outline" 
                        size="sm" 
                        onClick={handleDownload}
                        data-testid="button-download"
                      >
                        <Download className="h-4 w-4 mr-1" />
                        Download
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-6">
                  {generatedData.questions.map((category, categoryIndex) => (
                    <div key={categoryIndex}>
                      <div className="flex items-center gap-2 mb-3">
                        <Badge variant="secondary">{category.category}</Badge>
                      </div>
                      <ul className="space-y-2 pl-1">
                        {category.items.map((question, qIndex) => (
                          <li key={qIndex} className="flex items-start gap-2">
                            <ChevronRight className="h-4 w-4 mt-0.5 text-primary shrink-0" />
                            <span className="text-sm">{question}</span>
                          </li>
                        ))}
                      </ul>
                      {categoryIndex < generatedData.questions.length - 1 && (
                        <Separator className="mt-4" />
                      )}
                    </div>
                  ))}
                </CardContent>
              </Card>
            </>
          )}

          {!generatedData && !generateMutation.isPending && !generateMutation.isError && (
            <Card className="border-dashed">
              <CardContent className="flex flex-col items-center justify-center py-12 text-center">
                <ClipboardList className="h-12 w-12 text-muted-foreground/50 mb-4" />
                <h3 className="font-medium text-muted-foreground">No questions generated yet</h3>
                <p className="text-sm text-muted-foreground mt-1 max-w-sm">
                  Fill in the form with your health information and click "Generate Questions" 
                  to get personalized questions for your doctor visit.
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
